const catalogo = [
    {
      title: "Chimuelo y Lightfury",
      price: 3900,
      id: "1",
      image: "../src/Assets/mockimg/dragon.jpg",
      description: "",
      category: "figures",
      categoryName: "Figuras",
      size: "15cm c/u",
    },
    {
      title: "Groot Maceta",
      price: 2200,
      id: 2,
      image: "../src/Assets/mockimg/groot.jpg",
      description: "",
      category: "toys",
      size: "18cm",
    },
    {
      title: "Mano Merlina",
      price: 2600,
      id: 3,
      image: "../src/Assets/mockimg/hand.jpg",
      description: "",
      category: "figures",
      size: "16cm",
    },
    {
      title: "Llavero Defensa",
      price: 900,
      id: 4,
      image: "../src/Assets/mockimg/manopla.jpg",
      description: "",
      category: "keychains",
      size: "5cm",
    },
    {
      title: "Boonie",
      price: 2800,
      id: 5,
      image: "../src/Assets/mockimg/boonie.jpg",
      description: "",
      category: "toys",
      size: "12cm",
    },
    {
      title: "Cortante Cookie Gigante",
      price: 1600,
      id: 6,
      image: "../src/Assets/mockimg/cookie.jpg",
      description: "",
      category: "cutters",
      size: "18cm",
    },
    {
      title: "Busto Maradona",
      price: 3500,
      id: 7,
      image: "../src/Assets/mockimg/diego.jpg",
      description: "",
      category: "figures",
      size: "12cm",
    },
    {
      title: "Dragon Largo",
      price: 3200,
      id: 8,
      image: "../src/Assets/mockimg/dragon-dorado.jpg",
      description: "",
      category: "toys",
      size: "28cm",
    },
    {
      title: "Iguanitas",
      price: 900,
      id: 9,
      image: "../src/Assets/mockimg/iguanas.jpg",
      description: "",
      category: "toys",
      size: "12cm",
    },
    {
      title: "Litofania 'Donde Convergemos'",
      price: 3600,
      id: 10,
      image: "../src/Assets/mockimg/lito.jpg",
      description: "",
      category: "lithophanes",
      size: "18cm",
    },
    {
      title: "Llavero Chicas Superpoderosas",
      price: 450,
      id: 11,
      image: "../src/Assets/mockimg/llavero-csp.jpg",
      description: "",
      category: "keychains",
      size: "4cm",
    },
    {
      title: "Llavero Remeras Egresados",
      price: 400,
      id: 12,
      image: "../src/Assets/mockimg/llavero-remeras.jpg",
      description: "",
      category: "keychains",
      size: "3cm",
    },
    {
      title: "Llavero Tiendas",
      price: 400,
      id: 13,
      image: "../src/Assets/mockimg/llavero-tiendas.jpg",
      description: "",
      category: "keychains",
      size: "3cm",
    },
    {
      title: "Zombie",
      price: 1500,
      id: 14,
      image: "../src/Assets/mockimg/zombie.jpg",
      description: "",
      category: "toys",
      size: "11cm",
    },
  ];
  
  export default catalogo;